import Link from 'next/link';
import Script from 'next/script'
export default function Head() {

  return (
    <>

      {/* <Script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.8.2/angular.min.js"></Script>
      <Script src="https://code.jquery.com/jquery-3.6.4.min.js"></Script>
      <Script src="/jstree/jstree.js" />
      <Script src="/jstree/ngJsTree.js" /> */}
      <title>Information - Intelliegent - Innovation</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      {/* <link href="/lib/assets/global/plugins/jstree/themes/default/style.min.css" rel="stylesheet" />
      <script src="/lib/assets/global/plugins/jstree/jstree.js" type="text/javascript"></script>
      <script src="/lib/assets/global/plugins/jstree/ngJsTree.js" type="text/javascript"></script> */}

    </>
  );
}
